### ISSUE TITLE
Cambio di licenza a Creative Commons

### ISSUE THREAD

**Issue by VaiTon** [csunibo/asciidoc-thesis#14]
Secondo me non ha molto senso utilizzare una licenza estremamente poco permissiva come la AGPL per un progetto del genere, soprattutto perché:
- non si tratta di software 
- non può essere utilizzata per scopi commerciali senza l'aggiunta di una grossa mole di lavoro (ricerca)

Propongo quindi di convertire il progetto ad una CC BY o, se vogliamo essere più restrittivi, una CC BY-SA. Nel primo caso un lavoro derivato (che usa il template) dovrebbe solo includere l'attribuzione, nel secondo caso essere ri-condiviso come CC BY-SA.

Sinceramente voterei per la prima, visto che si tratta solamente di un template, ma fatemi sapere che cosa ne pensate. Se decidiamo di andare avanti dovremmo chiedere a tutti i contributori il loro ok per procedere.

**Comment by VaiTon** [comment]
cc @foxyseta @cristian-5

**Comment by foxyseta** [comment]
Oddio scusa sì pensavo di averti risposto sul gruppo Telegram scusa. Sono assolutamente d'accordo con te

**Comment by VaiTon** [comment]
> Oddio scusa sì pensavo di averti risposto sul gruppo Telegram scusa. Sono assolutamente d'accordo con te

Sisi avevi già risposto, ma comunque per rendere la discussione pubblica e rintracciabile una conferma anche qui è d'obbligo

**Comment by VaiTon** [comment]
@cristian-5 se sei d'accordo anche tu procediamo a cambiare la licenza

**Comment by VaiTon** [comment]
Procedo a convertire la licenza ad una CC BY-SA
