### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by foxyseta** [csunibo/asciidoc-thesis#3]
Quali pipeline sarebbero adatte per questo tipo di modello?

**Comment by cristian-5** [comment]
Questa è un'ottima domanda dato che non possiamo rilasciare nulla di pronto al momento forse è meglio fare un readme sul main che lo spiega; un branch incrementale "debug" dove facciamo le nostre prove varie e poi lo mergiamo a main. Poi faremo una release del pacchetto non appena abbiamo risposto alle esigenze principali. Non è un modello vero e proprio ma questo è un progetto relativamente piccolo, fammi sapere come ti sembra quest'idea.

**Comment by foxyseta** [comment]
In realtà pensavo a come come "controllare a ogni push su main che la sintassi Asciidoc sia corretta", e/o "fare una release con il pdf allegato a ogni push su main" (quindi ci/cd) per il tesista anziché per noi. Faccio riferimento a questa repo come "modello" nel senso che al momento è un template GitHub. Scegli pure tu il nome della branch a cui lavorare (forse "dev" anziché "debug"?"). Puoi liberamente aggiungere al README un disclaimer provvisorio se vuoi.
